name: check-pull-request-title
author: Wei Xu <xu.weiKyrie@foxmail.com>
description: Ensure your PR title matches the Pulsar Pull Request Naming Convention Guide (https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#).
branding:
  icon: 'check'
  color: 'green'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Execute
      run: go run .
      shell: bash
inputs:
  types:
    description: "Provide custom types."
    required: false
  scopes:
    description: "Configure which scopes are allowed."
    required: false
  headerPattern:
    description: "If you're using a format for the PR title that differs from the traditional Conventional Commits spec, you can use this to customize the parsing of the type, scope and subject. "
    required: false