name: "PR Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - uses: amannn/action-semantic-pull-request@v4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}