name: "PR Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: amannn/action-semantic-pull-request@v4
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            improve
            fix
            cleanup
            refactor
            revert

          scopes: |
            admin
            broker
            cli
            io
            fn
            meta
            monitor
            proxy
            schema
            sec
            sql
            storage
            offload
            txn
            java
            cpp
            py
            ws
            test
            ci
            build
            misc
            doc
            blog
            site

          headerPattern: '^(?:\[(\w*)\])?(?:\[([\w$.\-*/ ]*)\])?: (.*)$'