name: "Check PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - labeled
      - unlabeled

jobs:
  check-pr-title:
    if: github.event.action == 'opened' || github.event.action == 'edited'
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - run: go run ./main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
